const softwareEngineeringKeywords = [
  'agile',
  'algorithms',
  'angular',
  'authentication',
  'aws',
  'azure',
  'behaviordriven development',
  'circleci',
  'continuous deployment',
  'continuous integration',
  'c',
  'css',
  'database design',
  'django',
  'docker',
  'express.js',
  'expressjs',
  'flask',
  'functional programming',
  'git',
  'grpc',
  'graphql',
  'html',
  'java',
  'javascript',
  'jenkins',
  'kanban',
  'kotlin',
  'kubernetes',
  'microservices',
  'nodejs',
  'nosql',
  'objectoriented programming',
  'orm',
  'php',
  'python',
  'react',
  'rest',
  'restful apis',
  'ruby',
  'scrum',
  'security',
  'serverless architecture',
  'sql',
  'svn',
  'swift',
  'testdriven development',
  'travis ci',
  'typescript',
  'vuejs',
  'waterfall',
  'google cloud platform',
  'encryption',
];

const generalSoftSkillsKeywords = [
  'active listening',
  'adaptability',
  'analytical thinking',
  'collaboration',
  'conflict resolution',
  'continuous learning',
  'creativity',
  'curiosity',
  'empathy',
  'flexibility',
  'innovation',
  'leadership',
  'presentation skills',
  'prioritization',
  'selfmotivation',
  'time management',
  'troubleshooting',
  'verbal communication',
  'written communication',
];

export { softwareEngineeringKeywords, generalSoftSkillsKeywords };
