const softwareEngineeringKeywords = [
  'agile',
  'algorithms',
  'angular',
  'authentication',
  'aws',
  'azure',
  'behaviordriven development',
  'circleci',
  'continuous deployment',
  'continuous integration',
  'c',
  'css',
  'database design',
  'django',
  'docker',
  'express.js',
  'expressjs',
  'flask',
  'functional programming',
  'git',
  'grpc',
  'graphql',
  'html',
  'java',
  'javascript',
  'jenkins',
  'kanban',
  'kotlin',
  'kubernetes',
  'microservices',
  'nodejs',
  'nosql',
  'objectoriented programming',
  'orm',
  'php',
  'python',
  'react',
  'rest',
  'restful apis',
  'ruby',
  'scrum',
  'security',
  'serverless architecture',
  'sql',
  'svn',
  'swift',
  'testdriven development',
  'travis ci',
  'typescript',
  'vuejs',
  'waterfall',
  'google cloud platform',
  'encryption',
];

const generalSoftSkillsKeywords = [
  'active listening',
  'adaptability',
  'analytical thinking',
  'attention to detail',
  'communication',
  'conflict resolution',
  'continuous learning',
  'creativity',
  'critical thinking',
  'curiosity',
  'empathy',
  'flexibility',
  'initiative',
  'innovation',
  'leadership',
  'negotiation',
  'organization',
  'patience',
  'presentation skills',
  'prioritization',
  'problem-solving',
  'selfmotivation',
  'teamwork',
  'time management',
  'tolerance',
  'troubleshooting',
  'verbal communication',
  'written communication',
  'adaptation',
  'assertiveness',
  'collaboration',
  'cultural intelligence',
  'decision-making',
  'emotional intelligence',
  'ethics',
  'facilitation',
  'growth mindset',
  'interpersonal skills',
  'mentoring',
  'open-mindedness',
  'persuasion',
  'resilience',
  'resourcefulness',
  'self-awareness',
  'stress management',
  'teaching abilities',
  'team building',
  'time estimation',
  'vision',
];

export { softwareEngineeringKeywords, generalSoftSkillsKeywords };
